-- MySQL Script generated by MySQL Workbench
-- Sat Nov  5 00:31:22 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pokemon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pokemon` (
  `idPokemon` INT GENERATED ALWAYS AS () VIRTUAL,
  `Nome` VARCHAR(60) NOT NULL,
  `Altura` FLOAT NOT NULL,
  `Peso` FLOAT NOT NULL,
  `Vida` INT NOT NULL,
  `Ataque` INT NOT NULL,
  `Defesa` INT NOT NULL,
  `AtaqueSP` INT NOT NULL,
  `DefesaSP` INT NOT NULL,
  `Velocidade` INT NOT NULL,
  PRIMARY KEY (`idPokemon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Habilidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Habilidades` (
  `idHabilidade` INT GENERATED ALWAYS AS (),
  `Habilidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idHabilidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fraquezas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fraquezas` (
  `idFraquezas` INT GENERATED ALWAYS AS () VIRTUAL,
  `Fraqueza` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFraquezas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipos` (
  `idTipos` INT GENERATED ALWAYS AS (),
  `Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Habilidades_has_Pokemon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Habilidades_has_Pokemon` (
  `Habilidades_idHabilidade` INT NOT NULL,
  `Pokemon_idPokemon` INT NOT NULL,
  PRIMARY KEY (`Habilidades_idHabilidade`, `Pokemon_idPokemon`),
  INDEX `fk_Habilidades_has_Pokemon_Pokemon1_idx` (`Pokemon_idPokemon` ASC) VISIBLE,
  INDEX `fk_Habilidades_has_Pokemon_Habilidades_idx` (`Habilidades_idHabilidade` ASC) VISIBLE,
  CONSTRAINT `fk_Habilidades_has_Pokemon_Habilidades`
    FOREIGN KEY (`Habilidades_idHabilidade`)
    REFERENCES `mydb`.`Habilidades` (`idHabilidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Habilidades_has_Pokemon_Pokemon1`
    FOREIGN KEY (`Pokemon_idPokemon`)
    REFERENCES `mydb`.`Pokemon` (`idPokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fraquezas_has_Pokemon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fraquezas_has_Pokemon` (
  `Fraquezas_idFraquezas` INT NOT NULL,
  `Pokemon_idPokemon` INT NOT NULL,
  PRIMARY KEY (`Fraquezas_idFraquezas`, `Pokemon_idPokemon`),
  INDEX `fk_Fraquezas_has_Pokemon_Pokemon1_idx` (`Pokemon_idPokemon` ASC) VISIBLE,
  INDEX `fk_Fraquezas_has_Pokemon_Fraquezas1_idx` (`Fraquezas_idFraquezas` ASC) VISIBLE,
  CONSTRAINT `fk_Fraquezas_has_Pokemon_Fraquezas1`
    FOREIGN KEY (`Fraquezas_idFraquezas`)
    REFERENCES `mydb`.`Fraquezas` (`idFraquezas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fraquezas_has_Pokemon_Pokemon1`
    FOREIGN KEY (`Pokemon_idPokemon`)
    REFERENCES `mydb`.`Pokemon` (`idPokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipos_has_Pokemon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipos_has_Pokemon` (
  `Tipos_idTipos` INT NOT NULL,
  `Pokemon_idPokemon` INT NOT NULL,
  PRIMARY KEY (`Tipos_idTipos`, `Pokemon_idPokemon`),
  INDEX `fk_Tipos_has_Pokemon_Pokemon1_idx` (`Pokemon_idPokemon` ASC) VISIBLE,
  INDEX `fk_Tipos_has_Pokemon_Tipos1_idx` (`Tipos_idTipos` ASC) VISIBLE,
  CONSTRAINT `fk_Tipos_has_Pokemon_Tipos1`
    FOREIGN KEY (`Tipos_idTipos`)
    REFERENCES `mydb`.`Tipos` (`idTipos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tipos_has_Pokemon_Pokemon1`
    FOREIGN KEY (`Pokemon_idPokemon`)
    REFERENCES `mydb`.`Pokemon` (`idPokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Treinador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Treinador` (
  `idTreinador` INT GENERATED ALWAYS AS () VIRTUAL,
  `Nome` VARCHAR(45) NOT NULL,
  `XP` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idTreinador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pokebola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pokebola` (
  `idPokebola` INT GENERATED ALWAYS AS (),
  `Tipo` INT NOT NULL DEFAULT 1,
  `Treinador_idTreinador` INT NOT NULL,
  `Pokemon_idPokemon` INT NOT NULL,
  PRIMARY KEY (`idPokebola`, `Treinador_idTreinador`, `Pokemon_idPokemon`),
  INDEX `fk_Pokebola_Treinador1_idx` (`Treinador_idTreinador` ASC) VISIBLE,
  INDEX `fk_Pokebola_Pokemon1_idx` (`Pokemon_idPokemon` ASC) VISIBLE,
  CONSTRAINT `fk_Pokebola_Treinador1`
    FOREIGN KEY (`Treinador_idTreinador`)
    REFERENCES `mydb`.`Treinador` (`idTreinador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pokebola_Pokemon1`
    FOREIGN KEY (`Pokemon_idPokemon`)
    REFERENCES `mydb`.`Pokemon` (`idPokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
